name: shellcheck
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: shellcheck install
        working-directory: ${{ github.workspace }}
